using System.Text.Json.Serialization;

namespace PlanAndExecute
{
    /// <summary>
    /// An ordered list of steps generated by <see cref="Planner.GeneratePlanAsync"/>.
    /// </summary>
    internal class ExecutionPlan
    {
        /// <summary>The plan's steps, in the order they should be executed.</summary>
        [JsonPropertyName("steps")]
        public List<string> Steps { get; set; } = new();
    }
}
